[galini]
timelimit = 600

[branch_and_cut.bab]
absolute_gap = 1e-8
relative_gap = 1e-6
fbbt_timelimit = 10
obbt_timelimit = 60
obbt_simplex_maxiter = 100
fbbt_maxiter = 1

[branch_and_cut.initial_primal_search]
strategy = 'pooling'

[branch_and_cut.nlp_solver.options]
max_iter = 500
constr_viol_tol = 1e-3

[cuts_generator]
generators = ['outer_approximation', 'pooling']

[cuts_generator.pooling]
#root_node_only = true